name: new-issue

on: 
  issues:
    types: [opened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: node script
        run: node ./newissue.js ${{ github.event.issue.number }} "${{ github.event.issue.title }}" "${{ github.event.issue.body}}"
